# This is a basic workflow that is manually triggered

name: CODDE Manager Build


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Build CODDE Manager'
        # Default value if no value is explicitly provided
        default: 'CODDE'
        # Input has to be provided for the workflow to run
        required: true
  workflow_run:
    workflows: [ "Pylint" ]
    types:
      - completed
    branches:
      - main
      - release/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deb-build:
    needs: python-build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Get Version
      run: |
        echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
    - name: Get Description
      run: |
        echo "DESCRIPTION=$(sed -n '2{p;q}' README.md)" >> $GITHUB_ENV
    - name: Set version
      run: |
        gbp dch --debian-branch main --new-version ${{ env.version }}
    - name: Build deb package
      run: |
        fakeroot dpkg-buildpackage -b